### PR TITLE
RCODE range updated (values of 19, 20, and 21 added) according to htt…

### PR DESCRIPTION
**Pull request by MioMil**
RCODE range updated (values of 19, 20, and 21 added).

### CODE REVIEW

**Review by robin-raymond — CHANGES_REQUESTED** [review]
Fix looks good but I noticed the spacing is off because the original source has tabs but you do not. I'm not sure what tab spacing they used in the original source.

**Comment by robin-raymond** [comment]
@HoseynHeydari This is a potential fix. Please take a look.

**Comment by MioMil** [comment]
Spacing should be fine now.

**Review by robin-raymond — APPROVED** [review]

**Comment by robin-raymond** [comment]
The pointer at the SDK level needs to be updated @SergioOpenPeer now this has been merged.

**Pull request merged**
